### ISSUE TITLE
windows `zigcc-x86_64-unknown-linux-musl.bat` param too long

### ISSUE THREAD

**Issue by afpro** [rust-cross/cargo-zigbuild#129] opened 2023-04-27 21:11 UTC
```
  = note: warning: unsupported linker arg: -znoexecstack
          warning: unsupported linker arg: -zrelro
          warning: unsupported linker arg: -znow
          error(link): unable to spawn D:\app\zig\zig.exe: NameTooLong
          error: UnableToSpawnSelf
```

param for `zigcc-x86_64-unknown-linux-musl.bat` is too long for issue comment

**Comment by afpro** [comment] 2023-04-27 21:15
param contains many file path (200+) with only different suffix like 
```
<target_dir>/<my_crate_name>-d8307fd01e5dbad0.106x2xzlnzugj0a4.rcgu.o
<target_dir>/<my_crate_name>-d8307fd01e5dbad0.10segnhr83vtjlbd.rcgu.o
<target_dir>/<my_crate_name>-d8307fd01e5dbad0.11cbkd6vavdbo5xw.rcgu.o
<target_dir>/<my_crate_name>-d8307fd01e5dbad0.11iwf57snfrcyjrd.rcgu.o
```

**Comment by Gankra** [comment] 2023-08-11 14:49
This appears to be a dupe of https://github.com/rust-cross/cargo-zigbuild/issues/46

which was closed citing https://github.com/ziglang/zig/issues/10881 needing to be fixed

**Closed** 2023-08-15 09:42 UTC
